parser: '@typescript-eslint/parser'
extends:
  - standard
  - standard-react
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
rules:
  react/prop-types: 0
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true